language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - build-tools-26.0.1
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
before_install:
  - "./notify.sh"
script:
- "./gradlew clean assembleDebug"
notifications:
  email: false
  slack:
    secure: brEfRELSx+x83DFQqSbOJQJy5NsRH3j+n3udfr2k3K9tugnnq7+u9h4sLfwlIvjHKqYJqqiN9/u13W1FNsWkNQFcBLoUBSEK9UDi3HdCWGTcYt6GvlilOid9TH6dn5fksJ6ya/3pYCu6Xal9McIN4gwL7oNL5NOEboiPD5tLU2zE1rifABknlY/6jA7brTaIOdNSHTYUIKfhRkob6v4V7QapVaw8KUU881QoDp3DkDhgStL4bWX4YefYs2MgmXWtzA9Vb8XMgGuvAKVKOwyk4h2SQPJMDVgjDzqeRCGsmnYUapUQNxMCAcXhjZ2+PfbdO8C0d9QuYF3YynBdYfSyr8fyuDkxnZ8aLJV/OOIkFP+Z0AH8MbUaF/jL1SyPWRBwESNHUvj0OtH8r0XO9HcQtnoiAIZdlOJrq8m17Z2JWMrNIQw6//WSMp4cvjZZW9CKnalbhYP5rItag3m+ROywOvLv97gQ6kEtZwVUkHiOF3/ytKQxkZZt6eXc6Q3wnqXLkEV49gBQb9qjzGbAGD4FdjljnYdQRI1zmuFEcc1l0q+RDhWeieHgVbi1VugNIgVHVLiXXxp9G81bHJkgjqq8oXfBjFcWxgysPoHWJIdRVv865PClhgnPAecqo+LAUYuSYjZweopCwdymBWFX+9KsA6tQz9ZVhJqTLeSBPmzwzuI=
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$ANDROID_HOME"
env:
  global:
  - secure: "dJA0ekII6xdHTuS7rf5r75tjmzCmugOgp6W84hKUXt1C7tZunTMTLHsKmc/LEpc5xzumrwwILc/N4M8HQHrXbZR3lKbonwzaJZ+L0B4BKMS9q4Zw8k2Be5D9XmS6DPxzeMdhC9t8vT7mTwF6Z/DzNLf1+Yx4+rGLt7ub9PNy9bCIjs6e4NZIWg9PuSnF/KwXDyHsQ1FMPs7OKbg97k6Z2z8/jno/6549jFvlxXxp8LtueQlyAWXmI92Kk2ZvhbreXnOWdNATtPv6ntCJooZ/ud8LZR2x1LEviXUAike7ltBR4qX7HqU6z3ojr4h4ZafKAffkIbFpjdXwNRtP7gJ6F/T6vJ808D94vvNpriHqTc+6tv0PU0bF8UsCxwn+7PLrQgeZLj93YTloy4IfPCUWrETfT/ADgJLsr1E7aUj/GHAC1qerchs17Z/ByxWiv8yBjq2hBpbTAZkF0iSxaSyUD4P5PiSFuuLHsMOjB9hGFUi4Y3wCRaPf3WLr18GWfKKYSUIeSAeFdxK0lxgbVwuYuJ0fGMkgmdp3stXbKKPcOWaSCU1UOrirVxPK99hC/SWmNVsBF+pJJYwPbVG+5nRu02gxuorp0bPZg7uMoT79KkCoAt0Vi+eyS4ZU/OOWf1jYQYOup9gBG1tY6veMih1Vml+LsEAndkidz0tPCLJZ21Y="
  - secure: "T1ku+z4gmai6r8HcLgeT91JAte+FobOBg10no4AkYaz9Mj+cxNGmzu1NWPo/vs40RiU4oaMo24xMLXl9v0Z6NeLRjw7iCW7d7BNr/DoVknEaUEbJ7rsmehE6WuYQUFC1I2R1DUAYMB4eDoFwRNVebQvac4g+JeHZHzvAZeJWPjN8GASiCUBeLta+LO1nCSaR+iRtpHp0RhDj01zEbhFKiVNLlYcKp1espqAvUBYap4EGIHy99c5U90ojlFrvRZV+AzM7tVmMfUdBmVxQ2yPR/9aPuuQelSRm1XYPFDVoEL27tcXvrxp2WlzC9zsObmFMMDnU9YCs3HPA1IKmOK47G7bkidolzY/V8LbsC4/WZtUZNoaNolZKebMGxBCpRNThE73Vn8YlbfmL9lw7pZEL7p8qKY4J/XyueHfZ2Bm2NelWy7mbxOKA2GR6v3BPSkvqBDxIpWT3Dwdo/0k26UlD9+tVpD4PshLjoMJzyk1VYJAm+GSU3NXtR2x32QdMDPjDBWJ5GTd9ni9/k/gVcPRmj9jj1usjZDH6XfVH4pfxdXskXDy5zX3KTw2YMSJZKUzmv57X0WlxixrWzLRP+FjH8VNmAfQvIZf9dzEXlhPbs7T/JKSW9eMLP95AXu32vc3xM57hMXzGbSpYOiS/M0QAyezMZBQv3HsYh3IF4XC5T3s="
  - secure: "XSzA60nyOOtWh1ARsJiTwYZ9Ek2Gv4cq62Ef1AdfC8uf4kmFlmjFD5PR0ij0lB6cOyoDIWyVv5+AXirUthnKTVcMSshF0tHpW04H6lCviDOLLjPNT4AG46qXyygUmJSAYwiMqkdW/PoNqBUDp5GjYDo4Sja3MNYZ/2joi8HI9g3WGA5E907Izs/VtEXsTo2lhqgEYQ0M2eK6+jIo9RNaI2T2TSoAVIkk+olzCETjiXWWBTzpxE04T/Y/t/rm1gtfaCn2IBwqgyZtCa78Ehs5Wt/U/SwQU82yhpEpNTd/yb3YM6ufVVyjEV/V/SotGTSNJTBfNeAK7pJQYmqPTLgIRZzO0Bh4ie85rWJjBLPUDjssyfdbaYUboDKWDPqpGCte6I+CCyPcBN0c4gC2EVcWwqGXkm7A9AgZpJ4uOqmApkOhz1X1ZSWSqw1+oUWEwj4cbQVL0IDYg0QIyvhbTXkJIlcSEmA4IICy+fsb75PEw729o9ID9/3XcPS45JVHla6q5Od6m+/3vIm1SNbkqGA7hULdWPPY6kcrods2NhYkH38Aq7hDUqB8EAAQX7GL1ql5TVb9p+WUm6mpiuyguhJ9LF8VrfSHaxw6CKGl3eVf/VwhEkp9VtjOPsg9BsIN+WaiVTZPj83Dx8dAxLdQZtoO9l409EPyUdcle41R38uwglc="
after_success:
  - "./push.sh"

